name: myblivion
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bouncing_widget: ^2.0.0
  lottie: ^1.2.1
  delayed_display: ^2.0.0
  flutter_phone_direct_caller: ^2.1.0
  url_launcher: ^6.0.18
  google_fonts: ^2.3.1
  flutter_speed_dial: ^5.0.0+1
  app_settings: ^4.1.1
  percent_indicator: ^4.0.0
  image_picker: ^0.8.4+8
  rive: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - "images/star_wars.gif"

